---
- block:
    - name: Get latest release
      set_fact:
        latest_version: "{{ lookup('artis3n.github.latest_release', 'kubernetes-sigs/cluster-api') }}"
  when: clusterctl_version == "latest"

- name: Set version to download
  changed_when: false
  set_fact:
    clusterctl_version_to_install: |-
      {{ (clusterctl_version == "latest") | ternary(latest_version, clusterctl_version) }}

- import_tasks: clusterctl_version.yml

- name: Determine if new version needs to be installed
  changed_when: false
  set_fact:
    clusterctl_already_installed: |-
      {{ existing_version.rc == 0 and (existing_version["stdout"].find(clusterctl_version_to_install) != -1) }}

- block:
    - name: Determine outputs directories and binary paths
      set_fact:
        clusterctl_artifact_name: 'clusterctl-{{ (ansible_facts["os_family"] == "Darwin") | ternary("darwin", "linux") }}-amd64'
        clusterctl_dest: '/usr/local/bin/clusterctl'
      changed_when: false

    - name: Download clusterctl
      get_url:
        url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterctl_version_to_install }}/{{ clusterctl_artifact_name }}"
        dest: "{{ clusterctl_dest }}"
        mode: "u+x,g+x,o+x"

  when: not clusterctl_already_installed

- import_tasks: clusterctl_version.yml

- name: Assert that correct version of clusterctl is installed
  assert:
    that:
      - existing_version is defined
      - existing_version.rc == 0
      - existing_version.stdout.find(clusterctl_version_to_install) != -1
