---
dependency:
  name: galaxy
driver:
  name: podman
# TODO: determine platforms and remove -x
lint: |
  set -e
  yamllint .
  # ansible-lint -x 701 .
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
