---
- block:
    - name: Get latest release
      set_fact:
        latest_version: "{{ lookup('artis3n.github.latest_release', 'kubernetes-sigs/cluster-api-provider-aws') }}"
  when: clusterawsadm_version == "latest"

- name: Set version to download
  changed_when: false
  set_fact:
    clusterawsadm_version_to_install: |-
      {{ (clusterawsadm_version == "latest") | ternary(latest_version, clusterawsadm_version)}}

- import_tasks: clusterawsadm_version.yml

- name: Determine if new version needs to be installed
  changed_when: false
  set_fact:
    clusterawsadm_already_installed: |-
      {{ existing_version.rc == 0 and (existing_version["stdout"].find(clusterawsadm_version_to_install) != -1) }}

- block:
    - name: Determine outputs directories and binary paths
      set_fact:
        clusterawsadm_artifact_name: 'clusterawsadm-{{ (ansible_facts["os_family"] == "Darwin") | ternary("darwin", "linux") }}-amd64'
        clusterawsadm_dest: '/usr/local/bin/clusterawsadm'
      changed_when: false

    - name: Download clusterawsadm
      get_url:
        url: "{{ base_url }}/download/{{ clusterawsadm_version_to_install }}/{{ clusterawsadm_artifact_name }}"
        dest: "{{ clusterawsadm_dest }}"
        mode: "u+x,g+x,o+x"

  when: not clusterawsadm_already_installed

- import_tasks: clusterawsadm_version.yml

- name: Assert that correct version of clusterawsadm is installed
  assert:
    that:
      - existing_version is defined
      - existing_version.rc == 0
      - existing_version.stdout.find(clusterawsadm_version_to_install) != -1
